<form action="?" method="POST">
<fieldset>
	<legend>Please Login:</legend>
	<input type="text" name="username" id="username" placeholder="Username" maxlength="20" size="20" autofocus />
	<input type="password" name="password" id="password" placeholder="Password" maxlength="20" size="20" />
	<div class="inline_btn">
		<input type="submit" class="submit_btn" value="Login" />
	</div>
</fieldset>

</form>